name: Bug/Suggestion except third-party mod integration or porting requests
description: Do not write different problems/ideas in one issue, keep them separate
body:
  - type: dropdown
    id: modloader
    attributes:
      label: Mod loader
      options:
        - Please select
        - Fabric
        - NeoForge
        - Forge
        - Quilt
        - Other
    validations:
      required: true
  - type: input
    id: mc-version
    attributes:
      label: Minecraft version
      placeholder: eg. 1.21.1
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: Mod version
      placeholder: eg. 1.0.0
    validations:
      required: true
  - type: input
    id: modloader-version
    attributes:
      label: Modloader version
      description: |
        List the version of the mod loader you are using.
        If on Fabric, post the versions of both Fabric Loader and Fabric API.
      placeholder: "eg. NeoForge: 21.0.0 / Fabric: Loader 0.10.6 + API 0.42.1"
    validations:
      required: true
  - type: input
    id: modpack
    attributes:
      label: Modpack info
      description: |
        If you are playing a modpack, post the link to it!
  - type: checkboxes
    id: reproducible
    attributes:
      label: "[IMPORTANT] If bug:"
      options:
        - label: "I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods."
  - type: input
    attributes:
      label: "[IMPORTANT] If bug: The **latest.log** file, not the crash report"
      description: "Please use a paste site such as [gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc."
  - type: textarea
    attributes:
      label: Issue description
      placeholder: A description of the bug/suggestion.
